console.log ('NUMEROS'); 

var edad = 27, tiempo = 30

edad = edad + 1 //Para sumar numero a variables//

//edad+= 1 Tambien se pueden sumar de esta manera//
//edad-= 1 Tambien se pueden restar de esta manera//

edad = edad + tiempo //Para sumar variables//

var preciode3vino = 350.50

var precioporvino = Math.round(preciode3vino/3)

// Si queremos hacer algun calculo con decimales, utilizar math.round al principio y lo demas entre parentesis

// Si quieres que solo tome en cuenta tantos decimales despues de la coma, a la variable, colocale tofixed(2)

var pizza = 8
var personas = 4
var cantidaddeporciones

cantidaddeporciones = (pizza/personas)