console.log ('Hola mundo JS'); // Como hablarle a la consola //

var nombre; // Asi se define una variable//

nombre  = 'Jeikel' // Asi se asigna un valor a una variable//

//Tambien se puede colocar junto la declaracion y el valor//

var apellido = 'Sanchez'

// Tambien puedes declarar variables en una misma linea usando coma//

var segundoapellido = 'Juan' , segundonombre = 'Matias', edad = 28;

console.log ('Hola' + ' ' + nombre + ' ' + apellido + ' ' + 'Bienvenido al curso')
console.log ('Tengo' + ' ' + edad + ' ' + 'de edad')